- name: Deploy and configure web application
  hosts: web_servers
  become: true
  vars:
    repo_url: "git@github.com:ArtemSadovenko/ris-course-work.git"
    repo_directory: "/home/ubuntu/ris-course-work"
    build_directory: "/home/ubuntu/ris-course-work/dist"
    nginx_directory: "/var/www/html"
    
  tasks:
    - name: Add GitHub to known hosts
      ansible.builtin.shell: |
        ssh-keyscan -H github.com >> /home/ubuntu/.ssh/known_hosts
      args:
        creates: /home/ubuntu/.ssh/known_hosts

    - name: Ensure repository directory exists
      ansible.builtin.file:
        path: "{{ repo_directory }}"
        state: directory

    - name: Check if the repository is already cloned
      ansible.builtin.stat:
        path: "{{ repo_directory }}/.git"
      register: git_dir

    - name: Pull latest changes from the repository
      ansible.builtin.shell: |
        cd "{{ repo_directory }}" && git pull origin main
      args:
        chdir: "{{ repo_directory }}"
      become_user: "{{ ansible_user }}"
      when: git_dir.stat.exists

    - name: Install @vue/cli
      npm:
        name: "@vue/cli"
        global: true

    - name: Install node_modules
      command: npm install
      args:
        chdir:

    - name: Build
      ansible.builtin.shell: |
        npm run build
      args:
        chdir: "{{ repo_directory }}"
      environment:
        NODE_ENV: production

    - name: Copy build files to nginx directory
      ansible.builtin.copy:
        src: "{{ build_directory }}/"
        dest: "{{ nginx_directory }}"
        remote_src: yes
        owner: nginx
        group: nginx
        mode: "0755"

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
