---
- name: Deploy and configure web application
  hosts: web_servers
  become: true
  vars:
    repo_url: "git@github.com:ArtemSadovenko/ris-course-work.git"
    repo_directory: "{{ ansible_env.HOME }}/ris-course-work"
    build_directory: "{{ ansible_env.HOME }}/ris-course-work/dist"
    nginx_directory: "/var/www/html"
    
  tasks:
    - name: Ensure repository directory does not exist
      ansible.builtin.file:
        path: "{{ repo_directory }}"
        state: absent
      ignore_errors: true

    - name: Clone the repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_directory }}"
        version: main

    - name: Install npm dependencies and build
      ansible.builtin.shell: |
        npm install
        npm run build
      args:
        chdir: "{{ repo_directory }}"
      environment:
        NODE_ENV: production

    - name: Copy build files to nginx directory
      ansible.builtin.copy:
        src: "{{ build_directory }}/"
        dest: "{{ nginx_directory }}"
        remote_src: yes
        owner: nginx
        group: nginx
        mode: "0755"

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
