name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Configure Web Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Ansible and run the playbook
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Path to the playbook
          playbook: ./ansible/deployment-playbook.yml
          directory: ./

          # SSH private key from GitHub Secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Inventory with EC2 instance details
          inventory: |
            [web_servers]
            54.235.237.43 ansible_user=ubuntu ansible_host=54.235.237.43

          # Additional flags
          options: |
            --limit web_servers
